project_id = "snriaelgnlnuhfuiqsdt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.shopify-webhook]
verify_jwt = false

[functions.shopify-oauth]
verify_jwt = false

[functions.shopify-api]
verify_jwt = false

[auth]
enabled = true
port = 54325