// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snriaelgnlnuhfuiqsdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNucmlhZWxnbmxudWhmdWlxc2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTc0MjksImV4cCI6MjA3MTg5MzQyOX0.8U-gwC2-ATkpsZLG7KYnfd-U786HRoPQQu-BAy-6Dkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});